config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # devise_for :users
  root 'questions#index' , as:'home'
  resources :questions do
    resources :answers
  end

  namespace :api do
    namespace :v1 do
      get 'games'=>'games#index'
      post 'signin' , controller: :auth , action: :authenticate
      post 'signup' , controller: :auth , action: :signup
      delete 'signout' , controller: :auth , action: :signout
      post 'score' => 'games#create'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  #  Validation
  validates :description , presence: true ,length: { maximum: 500 }
  validates :point , presence: true ,numericality: true
  validates_associated :answers
  # Association
  has_many :answers ,dependent: :destroy
  accepts_nested_attributes_for :answers, :allow_destroy => true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_admin

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    # render plain: params[:post].inspect
    @answer_params = question_params[:answers]
    @answer_hash = Array.new
    @question = Question.new(question_params.except(:answers))
    if @question.save
      @answer_params[:description].each_with_index do |val, index|
        @answer_hash << {:description => val, :right => @answer_params[:right][index+1]}
      end
      @question.answers.create(@answer_hash)
      redirect_to @question
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
     @question.answers.build

  end

  def update
    # render plain: params[:post].inspect
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end


  private

  def question_params
    params.require(:question).permit(:point, :description, answers: [:description => [], :right => []])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<h2>Edit Question </h2>
<% if @question.errors.any? %>
  <% @question.errors.full_messages.each do |msg| %>
    <span class="alert alert-danger"><%= msg %></span>
  <% end %>
<% end %>
<%= form_for :question, url: question_path(@question), method: :patch do |f| %>
  <p>Description <br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>
  <p>Point <br>
    <%= f.number_field(:point, {:class => 'form-control'}) %>
  </p>

  <%= f.fields_for :answers do |answer| %>
    <pre><%= answer.text_field(answer: :description) %></pre>
    <div class=" form-group d-flex">
      <div>
        <label>Answer one</label>
        <%= answer.text_area(:description, {:class => 'form-control',multiple: true}) %>
        <div class="form-check">
          <%= answer.check_box(:right, {:class => 'form-check-input',multiple: true}) %>
          <label class="form-check-label" >Right</label>
        </div>
      </div>
      <div>
        <label>Answer Two</label>
        <%= answer.text_area(:description, {:class => 'form-control',multiple: true}) %>
        <div class="form-check">
          <%= answer.check_box(:right, {:class => 'form-check-input',multiple: true}) %>
          <label class="form-check-label" >Right</label>
        </div>
      </div>
      <div>
        <label>Answer Tree</label>
        <%= answer.text_area(:description, {:class => 'form-control',multiple: true}) %>
        <div class="form-check">
          <%= answer.check_box(:right, {:class => 'form-check-input',multiple: true}) %>
          <label class="form-check-label" >Right</label>
        </div>
      </div>
      <div>
        <label>Answer Fore</label>
        <%= answer.text_area(:description, {:class => 'form-control',multiple: true}) %>
        <div class="form-check">
          <%= answer.check_box(:right, {:class => 'form-check-input',multiple: true}) %>
          <label class="form-check-label" >Right</label>
        </div>
      </div>
    </div>
  <% end %>
  <%= f.submit({:class => 'btn btn-primary  '}) %>
<% end %>

app/views/questions/index.html.erb
<div class="d-flex justify-content-end ">
  <%= link_to "Create New Question" , new_question_path, :class => 'btn btn-outline-success' %>
</div>
<% @questions.each_with_index  do |question,index| %>
  <div class="alert alert-light">
    <p><span><%= index+1 %>. </span><%= question.description %></p>
    <%= link_to "Read More" , question_path(question), :class => 'btn btn-outline-success' %>
  </div>
<% end %>

app/views/questions/new.html.erb
<h2>New Question </h2>
<% if @question.errors.any? %>
  <% @question.errors.full_messages.each do |msg| %>
    <span class="alert alert-danger"><%= msg %></span>
  <% end %>
<% end %>
<%= form_for :question, url: questions_path, method: :post do |f| %>
  <p>Description <br>
    <%= f.text_area(:description, {:class => 'form-control'}) %>
  </p>
  <p>Point <br>
    <%= f.number_field(:point, {:class => 'form-control'}) %>
  </p>
  <hr>
  <%= f.fields_for :answers do |answer| %>
    <div class=" form-group d-flex">
        <div>
          <label>Answer one</label>
          <%= answer.text_area(:description, {:class => 'form-control',multiple: true}) %>
          <div class="form-check">
            <%= answer.check_box(:right, {:class => 'form-check-input',multiple: true}) %>
            <label class="form-check-label" >Right</label>
          </div>
        </div>
      <div>
        <label>Answer Two</label>
        <%= answer.text_area(:description, {:class => 'form-control',multiple: true}) %>
        <div class="form-check">
          <%= answer.check_box(:right, {:class => 'form-check-input',multiple: true}) %>
          <label class="form-check-label" >Right</label>
        </div>
      </div>
      <div>
        <label>Answer Tree</label>
        <%= answer.text_area(:description, {:class => 'form-control',multiple: true}) %>
        <div class="form-check">
          <%= answer.check_box(:right, {:class => 'form-check-input',multiple: true}) %>
          <label class="form-check-label" >Right</label>
        </div>
      </div>
      <div>
        <label>Answer Fore</label>
        <%= answer.text_area(:description, {:class => 'form-control',multiple: true}) %>
        <div class="form-check">
          <%= answer.check_box(:right, {:class => 'form-check-input',multiple: true}) %>
          <label class="form-check-label" >Right</label>
        </div>
      </div>
    </div>
  <% end %>
  <%= f.submit({:class => 'btn btn-primary'}) %>

<% end %>

app/views/questions/show.html.erb
<p><%= @question.description %></p>
<span>Point: <strong><%= @question.point %></strong></span>
<hr>
<%= link_to "Edit Question" , edit_question_path(@question) , :class => "btn btn-outline-warning" %>
<%= link_to "Delete Question" , question_path(@question) ,method: :delete, data:{confirm:'Are you sure?'}, :class => "btn btn-outline-danger" %>
<hr>
<h4>All Answers </h4>
<div class="d-flex">
  <% @question.answers.each do |answer| %>
    <p class="alert <%= answer.right === true ? 'alert-success' : 'alert-light' %>"><%= answer.description %></p>
  <% end %>
</div>